image: node:14

stages:
  - install
  - quality
  - lint

# Install
install:dependency:
   stage: install
   script:
      - npm install
   artifacts:
      name: "artifacts"
      #untracked: true
      expire_in: 30 mins
      paths:
        - node_modules/

# Unit test
test:unit:
   stage: quality
   script:
      -  npm run test
   dependencies:
      - "install:dependency"

# Linting and Formatting
lint:format:
   stage: lint
   script:
      - npm run format:check
